"""Regenerate worker/src/airports-data.js from the mwgg/Airports dataset (MIT license).

Run from the repository root: python3 scripts/build_airports.py
"""
import json
import urllib.request
from pathlib import Path

SOURCE = "https://raw.githubusercontent.com/mwgg/Airports/master/airports.json"
OUT = Path(__file__).resolve().parent.parent / "worker" / "src" / "airports-data.js"


def main() -> None:
    with urllib.request.urlopen(SOURCE, timeout=60) as response:
        airports = json.load(response)
    compact = {}
    for airport in airports.values():
        code = (airport.get("iata") or "").strip().upper()
        if len(code) == 3 and code.isalnum() and airport.get("tz"):
            compact[code] = [airport["name"], round(airport["lat"], 4), round(airport["lon"], 4), airport["tz"]]
    body = json.dumps(dict(sorted(compact.items())), ensure_ascii=False, separators=(",", ":"))
    OUT.write_text(
        "// Generated by scripts/build_airports.py from mwgg/Airports (MIT License,\n"
        "// https://github.com/mwgg/Airports). Fields: [name, lat, lon, IANA time zone].\n"
        f"export const AIRPORTS = {body};\n",
        encoding="utf-8",
    )
    print(f"Wrote {len(compact)} airports to {OUT}")


if __name__ == "__main__":
    main()
